name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Verify frontend directory
      run: ls -la ./frontend

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64,linux/arm64/v8
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

    - name: Logout from Docker Hub
      run: docker logout
